---
title: "SpaGene"
author: "Jin Huhao"
date: "2024-04-09"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(Seurat)
library(SeuratDisk)
library(spacexr)
library(Matrix)
library(dplyr)
library(ggplot2)
library(SpaGene)  
library(pheatmap)
library(gridExtra)
```

```{r}
path <- "D:/Desktop/MGI/CODE/"

# Data
data <- LoadH5Seurat(paste0(path, "Data/SS200000116BR_E6.bin200.h5seurat"))
head(data@meta.data, 5)
```

```{r}
coords <- data@meta.data %>% select(x, y)
coords
```

```{r}
counts = GetAssayData(data)
counts
```
```{r}
# Identify spatial variable genes based on spatial connectness of spots with high expression

# expr: gene expression matrix, the row is the gene and the column is the spot/cell
# location: location matrix, the row number of location should match the column number of expr
# normalize: default True

spa_gene <- SpaGene(expr = counts, location = coords)
```

```{r}
head(spa_gene$spagene_res[order(spa_gene$spagene_res$adjp),])
```

```{r}
pattern<-FindPattern(spa_gene)
```
```{r}
plotpattern <- function (pattern, location, max.cutoff = 0.9, pt.size = 2, 
  alpha.min = 0.1, aspect_ratio = 1) 
{
  if (!requireNamespace("RColorBrewer", quietly = TRUE)) {
    install.packages("RColorBrewer")
  }
  colnames(location) <- c("x", "y")
  npattern <- dim(pattern$pattern)[1]
  plist <- list()
  for (i in 1:npattern) {
    feature = pattern$pattern[i, ]
    max.use <- quantile(feature, max.cutoff)
    feature[feature > max.use] <- max.use
    alpha = (feature - min(feature))/(max(feature) - min(feature)) * 
      (1 - alpha.min) + alpha.min
    tmp <- as.data.frame(cbind(location, exp = feature, 
      alpha = alpha))
    p1 <- ggplot(tmp, aes(x = x, y = y, col = exp, alpha = alpha)) + 
      geom_point(size = pt.size) + 
      scale_color_gradientn(colours = rev(RColorBrewer::brewer.pal(n = 10, 
        name = "RdYlBu"))) + xlab("") + ylab("") + theme(axis.line = element_blank(), 
      axis.text.x = element_blank(), axis.text.y = element_blank(), 
      axis.ticks.x = element_blank(), axis.ticks.y = element_blank()) + 
      guides(color = "none", alpha = "none") + ggtitle(paste0("Pattern", 
      i)) + coord_fixed(ratio = aspect_ratio)
    plist[[i]] <- p1
  }
  patchwork::wrap_plots(plist)
}
```


```{r}
pattern_plots <- plotpattern(pattern, coords, pt.size = 1, aspect_ratio = 1.58)
```

```{r}
pattern_plots
```


```{r}
pattern_plots[[1]]
```
```{r}
weight <- pattern$patternw
weight
```

```{r}
top5<-apply(pattern$genepattern, 2, function(x){names(x)[order(x,decreasing=T)][1:5]})
top5
```
```{r}
pheatmap(pattern$genepattern[rownames(pattern$genepattern)%in%top5,])
```

```{r}
top5_in_pattern1 <- top5[, "Pattern1"]
top5_in_pattern1
```

```{r}
top5_df <- counts[top5_in_pattern1, ] %>% as.matrix() %>% t() %>% as.data.frame() 
top5_df
```
```{r}
top5_df <- cbind(top5_df, coords)
top5_df
```

```{r}
plots <- lapply(1:5, function(i) {

  cell_data <- top5_df[, c(i, 6, 7)]
  colnames(cell_data) <- c("Expression", "X", "Y")
  
  p <- ggplot(cell_data, aes(x = X, y = Y, color = Expression)) +
    geom_point(size = 1) +
    scale_color_gradient(low = "white", high = "red", limits = range(top5_df[,1:5])) +  
    labs(title = colnames(top5_df)[i])  
  
  return(p)
})

plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]
plots[[5]]
```









